:- module(seat_classes,[]).
class(a1, first).
class(e1, first).
class(f1, first).
class(k1, first).
class(a2, first).
class(e2, first).
class(f2, first).
class(k2, first).
class(a3, first).
class(e3, first).
class(f3, first).
class(k3, first).

class(d11, business).
class(g11, business).

class(a12, business).
class(e12, business).
class(f12, business).
class(k12, business).
class(b14, business).
class(d14, business).
class(g14, business).
class(j14, business).

class(a15, business).
class(e15, business).
class(f15, business).
class(k15, business).
class(b16, business).
class(d16, business).
class(g16, business).
class(j16, business).

class(a17, business).
class(e17, business).
class(f17, business).
class(k17, business).
class(b18, business).
class(d18, business).
class(g18, business).
class(j18, business).

class(a19, business).
class(e19, business).
class(f19, business).
class(k19, business).
class(b20, business).
class(d20, business).
class(g20, business).
class(j20, business).

class(a21, business).
class(e21, business).
class(f21, business).
class(k21, business).
class(b22, business).
class(d22, business).
class(g22, business).
class(j22, business).

class(a23, business).
class(e23, business).
class(f23, business).
class(k23, business).

class(b24, business).
class(j24, business).

class(a25, business).
class(d25, business).
class(g25, business).
class(k25, business).

class(b26, business).
class(e26, business).
class(f26, business).
class(j26, business).

class(a27, business).
class(d27, business).
class(g27, business).
class(k27, business).

class(a31, economy).
class(b31, economy).
class(c31, economy).
class(h31, economy).
class(j31, economy).
class(k31, economy).
class(a32, economy).
class(b32, economy).
class(c32, economy).
class(h32, economy).
class(j32, economy).
class(k32, economy).
class(a33, economy).
class(b33, economy).
class(c33, economy).
class(h33, economy).
class(j33, economy).
class(k33, economy).
class(a34, economy).
class(b34, economy).
class(c34, economy).
class(h34, economy).
class(j34, economy).
class(k34, economy).
class(a35, economy).
class(b35, economy).
class(c35, economy).
class(d35, economy).
class(e35, economy).
class(f35, economy).
class(g35, economy).
class(h35, economy).
class(j35, economy).
class(k35, economy).
class(a36, economy).
class(b36, economy).
class(c36, economy).
class(d36, economy).
class(e36, economy).
class(f36, economy).
class(g36, economy).
class(h36, economy).
class(j36, economy).
class(k36, economy).
class(a37, economy).
class(b37, economy).
class(c37, economy).
class(d37, economy).
class(e37, economy).
class(f37, economy).
class(g37, economy).
class(h37, economy).
class(j37, economy).
class(k37, economy).
class(a38, economy).
class(b38, economy).
class(c38, economy).
class(d38, economy).
class(e38, economy).
class(f38, economy).
class(g38, economy).
class(h38, economy).
class(j38, economy).
class(k38, economy).
class(a39, economy).
class(b39, economy).
class(c39, economy).
class(d39, economy).
class(e39, economy).
class(f39, economy).
class(g39, economy).
class(h39, economy).
class(j39, economy).
class(k39, economy).
class(a40, economy).
class(b40, economy).
class(c40, economy).
class(h40, economy).
class(j40, economy).
class(k40, economy).
class(a42, economy).
class(b42, economy).
class(c42, economy).
class(d42, economy).
class(e42, economy).
class(f42, economy).
class(g42, economy).
class(h42, economy).
class(j42, economy).
class(k42, economy).
class(a43, economy).
class(b43, economy).
class(c43, economy).
class(d43, economy).
class(e43, economy).
class(f43, economy).
class(g43, economy).
class(h43, economy).
class(j43, economy).
class(k43, economy).
class(a44, economy).
class(b44, economy).
class(c44, economy).
class(d44, economy).
class(e44, economy).
class(f44, economy).
class(g44, economy).
class(h44, economy).
class(j44, economy).
class(k44, economy).
class(a45, economy).
class(b45, economy).
class(c45, economy).
class(d45, economy).
class(e45, economy).
class(f45, economy).
class(g45, economy).
class(h45, economy).
class(j45, economy).
class(k45, economy).
class(a46, economy).
class(b46, economy).
class(c46, economy).
class(d46, economy).
class(e46, economy).
class(f46, economy).
class(g46, economy).
class(h46, economy).
class(j46, economy).
class(k46, economy).
class(a47, economy).
class(b47, economy).
class(c47, economy).
class(d47, economy).
class(e47, economy).
class(f47, economy).
class(g47, economy).
class(h47, economy).
class(j47, economy).
class(k47, economy).
class(a48, economy).
class(b48, economy).
class(c48, economy).
class(d48, economy).
class(e48, economy).
class(f48, economy).
class(g48, economy).
class(h48, economy).
class(j48, economy).
class(k48, economy).
class(a49, economy).
class(b49, economy).
class(c49, economy).
class(d49, economy).
class(e49, economy).
class(f49, economy).
class(g49, economy).
class(h49, economy).
class(j49, economy).
class(k49, economy).
class(a50, economy).
class(b50, economy).
class(c50, economy).
class(d50, economy).
class(e50, economy).
class(f50, economy).
class(g50, economy).
class(h50, economy).
class(j50, economy).
class(k50, economy).
class(a51, economy).
class(b51, economy).
class(c51, economy).
class(d51, economy).
class(e51, economy).
class(f51, economy).
class(g51, economy).
class(h51, economy).
class(j51, economy).
class(k51, economy).
class(a52, economy).
class(b52, economy).
class(c52, economy).
class(d52, economy).
class(e52, economy).
class(f52, economy).
class(g52, economy).
class(h52, economy).
class(j52, economy).
class(k52, economy).
class(a53, economy).
class(b53, economy).
class(c53, economy).
class(d53, economy).
class(e53, economy).
class(f53, economy).
class(g53, economy).
class(h53, economy).
class(j53, economy).
class(k53, economy).
class(a55, economy).
class(b55, economy).
class(c55, economy).
class(d55, economy).
class(e55, economy).
class(f55, economy).
class(g55, economy).
class(h55, economy).
class(j55, economy).
class(k55, economy).
class(a56, economy).
class(b56, economy).
class(c56, economy).
class(d56, economy).
class(e56, economy).
class(f56, economy).
class(g56, economy).
class(h56, economy).
class(j56, economy).
class(k56, economy).
class(a57, economy).
class(b57, economy).
class(c57, economy).
class(d57, economy).
class(e57, economy).
class(f57, economy).
class(g57, economy).
class(h57, economy).
class(j57, economy).
class(k57, economy).
class(a58, economy).
class(b58, economy).
class(c58, economy).
class(d58, economy).
class(e58, economy).
class(f58, economy).
class(g58, economy).
class(h58, economy).
class(j58, economy).
class(k58, economy).
class(a59, economy).
class(b59, economy).
class(c59, economy).
class(e59, economy).
class(f59, economy).
class(g59, economy).
class(h59, economy).
class(j59, economy).
class(k59, economy).

% FILL IN YOURS HERE +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
% ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

class(d75, economy).
class(e75, economy).
class(f75, economy).
class(g75, economy).

class(a76, economy).
class(b76, economy).
class(d76, economy).
class(e76, economy).
class(f76, economy).
class(g76, economy).
class(j76, economy).
class(k76, economy).
class(a77, economy).
class(b77, economy).
class(d77, economy).
class(e77, economy).
class(f77, economy).
class(g77, economy).
class(j77, economy).
class(k77, economy).
class(a78, economy).
class(b78, economy).
class(d78, economy).
class(e78, economy).
class(f78, economy).
class(g78, economy).
class(j78, economy).
class(k78, economy).

class(d79, economy).
class(e79, economy).
class(f79, economy).
class(g79, economy).

class(a80, economy).
class(b80, economy).
class(d80, economy).
class(e80, economy).
class(f80, economy).
class(g80, economy).
class(j80, economy).
class(k80, economy).
class(a81, economy).
class(b81, economy).
class(d81, economy).
class(e81, economy).
class(f81, economy).
class(g81, economy).
class(j81, economy).
class(k81, economy).
class(a82, economy).
class(b82, economy).
class(d82, economy).
class(e82, economy).
class(f82, economy).
class(g82, economy).
class(j82, economy).
class(k82, economy).

class(j83, economy).
class(k83, economy).
